import "./globals.css";
import { Public_Sans } from "next/font/google";
import localFont from "next/font/local";

import { Container } from "@/components/molecules";
import { Navbar } from "@/components/organisms";

const inter = Public_Sans({ subsets: ["latin"] });

export const spartan = localFont({
  src: [
    {
      path: "../../public/fonts/Spartan-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
});

type Props = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Simon H",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-light`}>
        <Navbar />
        <Container className="pt-8">{children}</Container>
      </body>
    </html>
  );
}
