import { Poppins, Public_Sans } from "next/font/google";
import localFont from "next/font/local";

import { Navbar } from "@/components/organisms";
import Head from "next/head";
import { AnimatePresence, motion } from "framer-motion";
import { usePathname } from "next/navigation";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const public_sans = Public_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const spartan = localFont({
  src: [
    {
      path: "../../../public/fonts/Spartan-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
});

type Props = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Simon H",
  description: "Generated by create next app",
};

export default function Layout({ children }: Props) {
  const path = usePathname();
  return (
    <div id="App" className={`${poppins.className} bg-light`}>
      <Head>
        <title>Simon Eychennes</title>
        <meta
          name="description"
          content="Virgile Hasselmann, a video and photo portfolio"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>
      <AnimatePresence mode="wait">
        <main key={path}>{children}</main>
      </AnimatePresence>
    </div>
  );
}
